"""add dtcai column

Revision ID: 675cede4db96
Revises: 
Create Date: 2025-05-26 11:39:10.372716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '675cede4db96'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lpplai')
    op.alter_column('stock_data', 'dtcai',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stock_data', 'dtcai',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.create_table('lpplai',
    sa.Column('Date', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Close', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('dtc', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('ai', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('dtcai', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('color', sa.VARCHAR(length=50), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
